import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.scss";
import "./normalize.scss";
import {Wrapper} from "@/src/Components/UI/Wrapper/Wrapper";
import {Header} from "@/src/Components/UI/Header/Header";
import {Footer} from "@/src/Components/UI/Footer/Footer";


export const metadata: Metadata = {
    title: "react next rakurs",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
            <Wrapper>
                <Header/>
                <main className='main'>
                    {children}
                </main>
                <Footer />
            </Wrapper>
        </body>
        </html>
    );
}
